USE [master]
GO

DELETE * FROM [dbo].[EPISODES];
DELETE * FROM [dbo].[FUNCTIONS];
DELETE * FROM [dbo].[GENRES];
DELETE * FROM [dbo].[PERSONS];
DELETE * FROM [dbo].[ROLES];
DELETE * FROM [dbo].[SCENES];
DELETE * FROM [dbo].[SEASONS];
DELETE * FROM [dbo].[TVSHOW_GENRES];
DELETE * FROM [dbo].[TVSHOWS];
GO